### ISSUE TITLE
Cursors

### ISSUE THREAD

**Issue by ondrej-bouda** [ondrej-bouda/ivory#4]
* Introduce support for cursors iterating over a relation.

**Comment by jkuchar** [comment]
I have done something [similar](https://gitlab.grifart.cz/jkuchar1/mappi-cursor), you can inspire yourself.

**Comment by ondrej-bouda** [comment]
Done. See the [`Ivory\Showcase\QueryingTest::testCursors()`](https://github.com/ondrej-bouda/ivory/blob/8d618ae7de1fc76b294aad047fac0034838d3970/test/unit/Ivory/Showcase/QueryingTest.php#L130) showcase test for overview of the features.
